# -*- coding: utf-8 -*-
"""Task-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/137fEbV55jwGTfH1hMBbzIsITbm1a6wZB
"""

import pandas as pd

data = pd.read_csv('/content/01.Data Cleaning and Preprocessing.csv')

data.head()

data.describe()

data.shape

data.info()



data.isnull()

data.isnull().sum()

data2 = data.fillna(value=0)
data2

data3 = data.fillna(method = 'pad')
data3

import numpy as np
from scipy import stats

data2.columns

data2.drop(['Observation'], axis = 1, inplace = True)
data2.columns

q1 = data2.quantile(0.25)
q2 = data2.quantile(0.75)

iqr = q2-q1
print(iqr)

data2 = data2[~((data2<(q1-1.5*iqr))|(data2>(q2+1.5*iqr))).any(axis=1)]
data2.shape

data2